name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: vanilla
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: frangio/test-push-2
          fetch-depth: 0
          path: upgradeable
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - run: |
          mv vanilla/README upgradeable/README
          cd upgradeable
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
